# =================================
# ZMK Studio ロック解除
# =================================
CONFIG_ZMK_STUDIO_LOCKING=n

CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# =================================
# マウス・スクロール機能を有効化する
# =================================
CONFIG_ZMK_POINTING=y

# ==========================
# LED（アンダーグロー）設定
# ==========================
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=n

# 起動時のデフォルトエフェクト（0:常時点灯, 1:ブレス）
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=0

# 起動時のデフォルトの明るさ（0〜100パーセント）
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=50