# =================================
# キースキャン（マトリックス検知）の強制有効化
# =================================
CONFIG_ZMK_KSCAN=y
CONFIG_ZMK_KSCAN_MATRIX_POLLING=y

# =================================
# ZMK Studio レイアウト編集機能
# =================================
CONFIG_ZMK_STUDIO=n
CONFIG_ZMK_STUDIO_LOCKING=n

# =================================
# マウス・スクロール機能を有効化する
# =================================
CONFIG_ZMK_POINTING=y

# ==========================
# LED（アンダーグロー）設定
# ==========================
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_LED_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=n

# 起動時のデフォルトエフェクト（0:常時点灯, 1:ブレス）
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=1

# 起動時のデフォルトの色を「紫」（280度）
CONFIG_ZMK_RGB_UNDERGLOW_HUE_START=280
CONFIG_ZMK_RGB_UNDERGLOW_SAT_START=100

# 起動時のデフォルトの明るさ（0〜100パーセント）
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=50

# ==========================
# パワーマネジメント（省電力）
# ==========================
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000